### ISSUE TITLE
Unable to Connect Issues

### ISSUE THREAD

**Issue by jvmahon** [DoctorMcKay/HSPI_LiftMasterMyQ#1]
The HSPI_LiftMasterMyQ plugin has been unable to connect to my account for a week or so.

I noticed on the HomeSeer forum for the similar plugin by kingfetty that users had been having the same problem, and it was noted that this may be due to a change in TLS encryption requirements used by the MyQ API. Could something similar be happening here? Are others having a problem with this plugin?

The forum comment referenced Linux (mono) - I'm having problems on a Windows 10 system, but maybe there is something analogous happening?

See https://forums.homeseer.com/forum/security-systems-plug-ins/security-system-discussion/liftmaster-myq-kingfetty/1311790-just-stopped-working?p=1313662#post1313662

**Comment by DoctorMcKay** [comment]
[v1.3.7133.39646](https://github.com/DoctorMcKay/HSPI_LiftMasterMyQ/releases/tag/v1.3.7133.39646) should fix this.

**Comment by jvmahon** [comment]
Does not seem to work..  Plugin status shows as either "Warning: An error occurred while sending the request" or else I get a "Critical plugin has disconnected" warning. I tried deleting the plugin as well as its config. information and re-installing. Still get these errors.

If there is a log file or anything else that I can send to help diagnose this, let me know (I didn't see where the log file is stored so if there is one, let me know that too). Thanks.
